import React from "react";

import Head from 'next/head';

import Logo from '../assets/logo.svg';
import { Container } from "../styles/Pages/home";



const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <h1>Hello world</h1>
        <Logo />
      </main>
    </Container>
  )
}

export default Home;
