import React from "react";

import Head from 'next/head';

import theme from "../styles/theme";
import theme2 from "../styles/theme2";

import Logo from '../assets/logo.svg';
import { Container } from "../styles/Pages/home";
import Banner from "../components/Banner";
import { ThemeProvider } from "styled-components";



const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <ThemeProvider theme={theme2}>
        <h1>Hello world</h1>
        <Logo />
        <Banner />
      </ThemeProvider>
    </Container>
  )
}

export default Home;
